version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_repuestos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repuesto
      MYSQL_USER: vcofre
      MYSQL_PASSWORD: vcofre123
    ports:
      - "3311:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql